### ISSUE TITLE
how can I get Calvis dataset of 8 meshes?

### ISSUE THREAD

**Issue by asimniazi63** [neoglez/calvis#2]
need it for quick experiments. Thank you, much appreciated

**Comment by neoglez** [comment]
Download from https://cloudlogin03.world4you.com/index.php/s/KC8N9YFKDFUm6Du
Password: calvis-8-hm

**Comment by asimniazi63** [comment]
The password is wrong. Please check

**Comment by neoglez** [comment]
Yeap, you're right. It should work now.

**Comment by asimniazi63** [comment]
file not found. Please update the link. thanks

**Comment by neoglez** [comment]
The link is in readme:
https://cloudlogin03.world4you.com/index.php/s/x2PvyP21UUn84tO

**Comment by zmhsmart** [comment]
Why does the compressed package after downloading show that it is damaged and cannot be compressed?

**Comment by neoglez** [comment]
@zmhsmart If with *package* you mean the [small Calvis dataset (8 meshes)](https://cloudlogin03.world4you.com/index.php/s/x2PvyP21UUn84tO), then I can assure you the download and unpacking works perfectly. You can [open this notebook in Colab](https://github.com/neoglez/calvis/blob/master/notebook/download_calvis_8_meshes.ipynb) to see the download and unpacking/decompressing in real time.
