### ISSUE TITLE
Dataset extraction error

### ISSUE THREAD

**Issue by himmetozcan** [neoglez/calvis#4]
Hi there,

Thanks for the dataset you provided. I have downloaded the whole dataset. When I try to extract the files to the folder, there is an error. I tried downloading it again, but it seems the files are corrupted.

![image](https://user-images.githubusercontent.com/44242024/153755368-46b605ca-11d7-4179-a68d-af2933c629bb.png)

**Comment by neoglez** [comment]
Hi,
that's a problem with your unzipping programm:
[Google "headers error there are some data after the end of the payload data"](https://www.google.com/search?q=headers+error+there+are+some+data+after+the+end+of+the+payload+data&oq=headers+error+there+are+some+data+fter+&aqs=chrome.1.69i57j0i13j0i22i30.23222j0j7&sourceid=chrome&ie=UTF-8)

E.g., [this entry](https://appuals.com/fix-there-are-some-data-after-the-end-of-the-payload-data/#:~:text=A%207%2DZip%20bug%20%E2%80%93%20The,but%20only%20on%20older%20builds.&text=Although%20the%20developers%20haven't,on%20certain%20types%20of%20data.) should solve your problem.
